# Cisco 7609

LEDAmount = 132
Linecards = [
    "6478",
    "6704",
    "blank",
    "6704",
    "sup720",
    "6704",
    "blank",
    "6704",
    "6478",
]
Patterns = ["blink48ports", "greenstatus", "sup720", "x6704"]
Mapping = [
    { gen = 1 },
    { card = 0 },
    { gen = 1 },
    { card = 8 },
    { card = 7 },
    { card = 5 },
    { gen = 1 },
    { card = 4 },
    { card = 3 },
    { gen = 1 },
    { card = 1 },
]
Buttons = []

[traffic_shaper]
enabled = true
peak_start = 17
peak_end = 22
low_start = 2
low_end = 7
peak_factor = 1.0
low_factor = 0.2

[output.ddp]
host = "127.0.0.1"
port = 4048
