# ASR 9010

LEDAmount = 200
Linecards = [
    "a9k-40ge-l",
    "a9k-8t-l",
    "blank",
    "a9k-8t-l",
    "a9k-rsp400-se",
    "a9k-rsp400-se-2",
    "a9k-8t-l",
    "blank",
    "a9k-8t-l",
    "a9k-40ge-l",
]
Mapping = [
    { card = 0 },
    { card = 1 },
    { card = 3 },
    { card = 4 },
    { card = 5 },
    { card = 6 },
    { card = 7 },
    { card = 8 },
    { card = 9 },
]
Patterns = ["greenstatus", "a9k-40ge-l", "a9k-8t-l", "a9k-rsp440-tr"]
#Patterns = ["mapper"]
Buttons = [
    { pin = "GPIO23", action = [
        "greenstatus",
        "a9k-8t-l",
        "a9k-40ge-l",
        "a9k-rsp400-se",
    ] },
    { pin = "GPIO24", action = [
    ] },
    { pin = "GPIO25", action = [
    ] },
    { pin = "GPIO16", action = [
    ] },
]

[traffic_shaper]
enabled = true
peak_start = 17
peak_end = 22
low_start = 2
low_end = 7
peak_factor = 1.0
low_factor = 0.2

[output.ddp]
host = "127.0.0.1"
port = 4048

# LED SEQUENCE
# a9k40  0  41
# 8k 41 50
# 8k 50 59
# rsp 69 70
# rsp 70 81
# 8k 81 90
# 8k 90 99
# a9k40 99 140